### PR TITLE
Add TLS support

### PR DESCRIPTION
**Pull request by tee-too**
Add support for TLS.

### CODE REVIEW

**Comment by moosingin3space** [comment]
Hey, looks good! Could you add an example config using TLS to the readme?

**Comment by tee-too** [comment]
English is not my native language. Do not hesitate to revise!

**Comment by moosingin3space** [comment]
The language looks fine.

I'd like there to be a possibility of using `rustls`, as that could be used to produce fully-statically-linked binaries (great for Docker). @alexcrichton do you know if `tokio-tls` can use `rustls` as a backend?

**Comment by moosingin3space** [comment]
Also, we need to add TLS support on the client side -- e.g. if I'm proxying to an HTTPS-only site. @seanmonstar, do you know how to do this with Hyper?

**Comment by seanmonstar** [comment]
Yep, you can supply any connector you want for the `Client`. A simple version using native-tls is here: https://github.com/hyperium/hyper-tls

**Comment by alexcrichton** [comment]
Currently a rustls backend doesn't exist, but I'd love to see one exist! Something like tokio-tls should definitely be able to use rustls as a backend

**Comment by tee-too** [comment]
Porting to `rustls`, but it is not as easy as using `tokio-tls` with `native-tls`. Nevertheless, this is a work in progress.

**Comment by moosingin3space** [comment]
In that case, I think I'll just merge the native-tls one. Rustls should be supported in tokio-tls, not something local to my proxy. 
@tee-too thanks for your contribution!

**Comment by tee-too** [comment]
OK. Then, I focus on TLS support on client side then.

**Comment by moosingin3space** [comment]
I'm gonna run some tests on my local machine (until I have CI set up) then merge this. Good job!

**Comment by moosingin3space** [comment]
Okay, so this crashes when a plaintext HTTP request is sent instead of an HTTPS request. Could you add a check to make sure it simply logs the error instead of crashing?

Otherwise, this looks great! Fix that and I'll merge!

**Pull request merged**
